stages:
  - build

variables:
  CONAN_REFERENCE: "breakpad/64"
  CONAN_USERNAME: "hgs"
  CONAN_UPLOAD: "https://api.bintray.com/conan/hgs/arsen-deps"
  CONAN_DOCKER_USE_SUDO: "False"
  CONAN_BUILD_TYPES: "Release"
  CONAN_ARCHS: "x86_64"

before_script:
  - apt-get update -yqq
  - apt-get install python-dev python-pip cmake git -yqq
  - pip install conan conan_package_tools
  - conan user

build:gcc-5:
  image: gcc:5
  variables:
    CONAN_GCC_VERSIONS: 5
  stage: build
  script: 
    - python build.py

build:gcc-6:
  image: gcc:6
  variables:
    CONAN_GCC_VERSIONS: 6
  stage: build
  script: 
    - python build.py

build:gcc-7:
  image: gcc:7
  variables:
    CONAN_GCC_VERSIONS: 7
  stage: build
  script: 
    - python build.py

build:clang-5:
  image: buildpack-deps:stretch
  variables:
    CONAN_CLANG_VERSIONS: "5.0"
  stage: build
  before_script:
    - curl -sL http://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
    - echo "deb http://apt.llvm.org/stretch/ llvm-toolchain-stretch-5.0 main" > /etc/apt/sources.list.d/llvm.list
    - clang -v
    - apt-get update -yqq
    - apt-get install clang-5.0 python-dev python-pip cmake git -yqq
    - pip install conan conan_package_tools
  script:
    - python build.py

build:clang-6:
  image: buildpack-deps:stretch
  variables:
    CONAN_CLANG_VERSIONS: "6.0"
  stage: build
  before_script:
    - curl -sL http://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
    - echo "deb http://apt.llvm.org/stretch/ llvm-toolchain-stretch-6.0 main" > /etc/apt/sources.list.d/llvm.list
    - clang -v
    - apt-get update -yqq
    - apt-get install clang-6.0 python-dev python-pip cmake git -yqq
    - pip install conan conan_package_tools
  script:
    - python build.py
