os: linux
language: python
sudo: required
services:
  - docker
env:
  global:
    - CONAN_UPLOAD: 1
    - CONAN_REFERENCE: "breakpad/1.0.0"
    - CONAN_USERNAME: "shinichy"
    - CONAN_CHANNEL: "ci"
    - CONAN_TOTAL_PAGES: 1

matrix:
   include:
       - os: osx
         osx_image: xcode8 # apple-clang 8.0
         language: generic
         env: CONAN_CURRENT_PAGE=1
       - os: osx
         osx_image: xcode7.3 # apple-clang 7.3
         language: generic
         env: CONAN_CURRENT_PAGE=1

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
